spring:
  profiles: production
  application:
    name: application-account
  cloud:
    config:
      uri: http://127.0.0.1:8080/
      failFast: true
      password: uiiui747h74f4e74eu45748bb44rfn7845nhd74ndeundnd63rgff6r
      username: user
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wallet?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
server:
  port: 8085
